//! Metal GPU backend for Fate.
//!
//! Dispatches N Fate inference instances in a single Metal kernel call.
//! Each GPU thread processes one 22-byte input record
//! (16 features + 1 model index + 5 biases) and returns one output byte.
//!
//! Enabled by the `metal` feature flag.

use crate::{Features, Model};
use metal::{Device, MTLResourceOptions, MTLSize};

/// MSL source generated by build.rs from brainfuck/fate.bf.
const FATE_METAL_SRC: &str = include_str!(concat!(env!("OUT_DIR"), "/fate.metal"));

// ---------------------------------------------------------------------------
// MetalRuntime
// ---------------------------------------------------------------------------

/// GPU-accelerated Fate runtime.
///
/// Dispatches N inference instances in a single Metal kernel, one thread per
/// instance. All instances run in parallel; the host blocks until all are done.
pub struct MetalRuntime {
    device: Device,
    queue: metal::CommandQueue,
    pipeline: metal::ComputePipelineState,
}

impl MetalRuntime {
    /// Discover the default Metal device and compile the kernel.
    ///
    /// Returns `Err` if no Metal device is available (non-Apple hardware or
    /// software-rendering fallback) or if MSL compilation fails.
    pub fn new() -> Result<Self, String> {
        let device =
            Device::system_default().ok_or_else(|| "No Metal device available".to_string())?;

        let queue = device.new_command_queue();

        let library = compile_library(&device, FATE_METAL_SRC)?;

        let function = library
            .get_function("fate_bf", None)
            .map_err(|e| format!("get_function fate_bf: {:?}", e))?;

        let pipeline = device
            .new_compute_pipeline_state_with_function(&function)
            .map_err(|e| format!("new_compute_pipeline_state: {:?}", e))?;

        Ok(MetalRuntime {
            device,
            queue,
            pipeline,
        })
    }

    /// Run `count` Fate instances in parallel.
    ///
    /// `inputs` must be exactly `count * 22` bytes: each contiguous 22-byte
    /// slice is one instance's input (16 features + 1 model index + 5 biases).
    ///
    /// Returns `count` output bytes — one per instance.
    pub fn run_batch(&self, inputs: &[u8], count: usize) -> Vec<u8> {
        assert_eq!(
            inputs.len(),
            count * 22,
            "inputs must be count * 22 bytes; got {} for count {}",
            inputs.len(),
            count
        );

        // Input buffer — shared CPU/GPU memory (managed).
        let input_buf = self.device.new_buffer_with_data(
            inputs.as_ptr() as *const _,
            (count * 22) as u64,
            MTLResourceOptions::StorageModeShared,
        );

        // Output buffer — one byte per instance.
        let output_buf = self
            .device
            .new_buffer(count as u64, MTLResourceOptions::StorageModeShared);

        // Encode and dispatch.
        let cmd_buf = self.queue.new_command_buffer();
        let encoder = cmd_buf.new_compute_command_encoder();

        encoder.set_compute_pipeline_state(&self.pipeline);
        encoder.set_buffer(0, Some(&input_buf), 0);
        encoder.set_buffer(1, Some(&output_buf), 0);

        let threads_per_grid = MTLSize {
            width: count as u64,
            height: 1,
            depth: 1,
        };
        let max_tg = self.pipeline.max_total_threads_per_threadgroup();
        let tg_width = max_tg.min(count as u64);
        let threads_per_group = MTLSize {
            width: tg_width,
            height: 1,
            depth: 1,
        };

        encoder.dispatch_threads(threads_per_grid, threads_per_group);
        encoder.end_encoding();

        cmd_buf.commit();
        cmd_buf.wait_until_completed();

        // Copy results out.
        let ptr = output_buf.contents() as *const u8;
        let slice = unsafe { std::slice::from_raw_parts(ptr, count) };
        slice.to_vec()
    }

    /// Run a tournament: evaluate `n` Fate instances against the same features.
    ///
    /// Creates `n` excited Fate instances (each with `Weights::default_cycle()`
    /// biases), encodes each instance's weights + the shared features into the
    /// flat input buffer, dispatches all in one kernel call, and decodes each
    /// output byte back to a `Model`.
    ///
    /// In the default-cycle weight set all instances are identical, so every
    /// thread will return the same model — this is the base case. Callers who
    /// want diverging results should inject varied weights directly via
    /// `run_batch`.
    pub fn tournament(&self, features: &Features, n: usize) -> Vec<Model> {
        use crate::fate::runtime::FateRuntime;
        use crate::fate::weights::Weights;

        let weights = Weights::default_cycle();
        let mut inputs = Vec::with_capacity(n * 22);

        for i in 0..n {
            let model_idx = (i % 5) as u8;
            let bias = &weights.sets[model_idx as usize].bias;
            let encoded = FateRuntime::encode_input_with_bias(model_idx, features, bias);
            inputs.extend_from_slice(&encoded);
        }

        let raw = self.run_batch(&inputs, n);
        raw.iter()
            .map(|&b| FateRuntime::decode_output(&[b]))
            .collect()
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn compile_library(device: &Device, src: &str) -> Result<metal::Library, String> {
    let options = metal::CompileOptions::new();
    device
        .new_library_with_source(src, &options)
        .map_err(|e| format!("MSL compile error: {:?}", e))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{runtime::FateRuntime, FEATURE_DIM, MODELS};

    fn zero_features() -> Features {
        [0.0; FEATURE_DIM]
    }

    fn make_runtime() -> Option<MetalRuntime> {
        MetalRuntime::new().ok()
    }

    /// GPU output must match the compiled CPU runtime for all five models
    /// with zero features.
    #[test]
    fn metal_matches_compiled() {
        let Some(gpu) = make_runtime() else {
            eprintln!("  metal_matches_compiled: skipped (no Metal device)");
            return;
        };

        let features = zero_features();

        for &model in &MODELS {
            // Build the 22-byte input the same way the CPU runtime does.
            let input = FateRuntime::encode_input(model, &features);
            let cpu_output = crate::fate::compiled::fate_bf(&input);
            let cpu_model = FateRuntime::decode_output(&cpu_output);

            let gpu_raw = gpu.run_batch(&input, 1);
            let gpu_model = FateRuntime::decode_output(&gpu_raw);

            assert_eq!(
                cpu_model, gpu_model,
                "GPU/CPU mismatch for {:?}: cpu={:?} gpu={:?}",
                model, cpu_model, gpu_model
            );
        }
    }

    /// 1 000 identical instances all agree on the same output.
    #[test]
    fn metal_batch_parallel() {
        let Some(gpu) = make_runtime() else {
            eprintln!("  metal_batch_parallel: skipped (no Metal device)");
            return;
        };

        let features = zero_features();
        let n = 1_000;

        // All 1 000 instances use the same input: Abyss + zero features.
        let one_input = FateRuntime::encode_input(Model::Abyss, &features);
        let inputs: Vec<u8> = one_input.iter().cloned().cycle().take(n * 22).collect();

        let results = gpu.run_batch(&inputs, n);

        let expected = results[0];
        for (i, &r) in results.iter().enumerate() {
            assert_eq!(
                r, expected,
                "instance {} produced {:?}, expected {:?}",
                i, r, expected
            );
        }
    }

    /// Tournament over all five model contexts returns `n` decoded Models.
    #[test]
    fn metal_tournament_excited() {
        let Some(gpu) = make_runtime() else {
            eprintln!("  metal_tournament_excited: skipped (no Metal device)");
            return;
        };

        let features = zero_features();
        let n = 25; // 5 models × 5 rounds

        let results = gpu.tournament(&features, n);
        assert_eq!(results.len(), n, "tournament should return n results");

        // Every result must be a valid Model (decode_output never panics, but
        // values outside 0-4 fall back to Abyss — verify none are unexpected).
        for r in &results {
            assert!(
                matches!(
                    r,
                    Model::Abyss
                        | Model::Introject
                        | Model::Cartographer
                        | Model::Explorer
                        | Model::Fate
                ),
                "unexpected model variant {:?}",
                r
            );
        }
    }
}
